name: BAUtility
main: com.battleasya.bautility.BAUtility
version: 2.0.4c
api-version: 1.14
author: Dennie
website: http://battleasya.com
description: BattleAsya Utility
commands:
  abc:
    description: Anti-Cheat broadcast.
  bbc:
    description: Big broadcast.
  nbc:
    description: Name broadcast.
  sbc:
    description: Staff broadcast.
  tbc:
    description: Title broadcast.
permissions:
  staffbc.use:
    description: Ability to broadcast.
    default: op